/*

 ROOM7MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 11
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room7Map_h_INCLUDE
#define __room7Map_h_INCLUDE

#define room7MapWidth 11
#define room7MapHeight 11
#define room7MapBank 0

extern const unsigned char room7Map[];

#endif

/* End of ROOM7MAP.H */
