/*

 ROOM8MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 26 x 20
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room8Map_h_INCLUDE
#define __room8Map_h_INCLUDE

#define room8MapWidth 26
#define room8MapHeight 20
#define room8MapBank 0

extern const unsigned char room8Map[];

#endif

/* End of ROOM8MAP.H */
