/*

 ROOM0MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 18
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room0Map_h_INCLUDE
#define __room0Map_h_INCLUDE

#define room0MapWidth 10
#define room0MapHeight 18
#define room0MapBank 0

extern const unsigned char room0Map[];

#endif

/* End of ROOM0MAP.H */
