/*

 ROOM4MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 26
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room4Map_h_INCLUDE
#define __room4Map_h_INCLUDE

#define room4MapWidth 20
#define room4MapHeight 26
#define room4MapBank 0

extern const unsigned char room4Map[];

#endif

/* End of ROOM4MAP.H */
