/*

 ROOM1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 26 x 18
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room1Map_h_INCLUDE
#define __room1Map_h_INCLUDE

#define room1MapWidth 26
#define room1MapHeight 18
#define room1MapBank 0

extern const unsigned char room1Map[];

#endif

/* End of ROOM1MAP.H */
