/*

 ROOM3MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 26
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room3Map_h_INCLUDE
#define __room3Map_h_INCLUDE

#define room3MapWidth 20
#define room3MapHeight 26
#define room3MapBank 0

extern const unsigned char room3Map[];

#endif

/* End of ROOM3MAP.H */
