/*

 ROOM6MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 24
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room6Map_h_INCLUDE
#define __room6Map_h_INCLUDE

#define room6MapWidth 16
#define room6MapHeight 24
#define room6MapBank 0

extern const unsigned char room6Map[];

#endif

/* End of ROOM6MAP.H */
