/*

 ROOM9MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 15 x 22
   Tile set      : forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room9Map_h_INCLUDE
#define __room9Map_h_INCLUDE

#define room9MapWidth 15
#define room9MapHeight 22
#define room9MapBank 0

extern const unsigned char room9Map[];

#endif

/* End of ROOM9MAP.H */
