/*

 BATTLEANIMMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\Ningami\raw graphics\shieldAnimTiles.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 240
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __battleAnimMap_h_INCLUDE
#define __battleAnimMap_h_INCLUDE

#define battleAnimMapWidth 2
#define battleAnimMapHeight 2
#define battleAnimMapBank 0

extern const unsigned char battleAnimMaps[3][4];

#endif

/* End of BATTLEANIMMAP.H */
