/*

 BATTLEANIMMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : C:\Projects\Gameboy\Ningami\raw graphics\shieldAnimTiles.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 240
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define battleAnimMapWidth 2
#define battleAnimMapHeight 2
#define battleAnimMapBank 0

const unsigned char battleAnimMaps[3][4] =
{
  { 0xF0,0xF2,0xF1,0xF3 },
  { 0xF4,0xF6,0xF5,0xF7 },
  { 0xF8,0xFA,0xF9,0xFB }
};

/* End of BATTLEANIMMAP.C */
