/*

 ENEMYMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : enemyKitsuneTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 224
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define enemyMapWidth 4
#define enemyMapHeight 4
#define enemyMapBank 0

const unsigned char enemyMap[] =
{
  0xE0,0xE2,0xE8,0xEA,0xE1,0xE3,0xE9,0xEB,0xE4,0xE6,
  0xEC,0xEE,0xE5,0xE7,0xED,0xEF
};

/* End of ENEMYMAP.C */
