/*

 ENEMYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : enemyKitsuneTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 224
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __enemyMap_h_INCLUDE
#define __enemyMap_h_INCLUDE

#define enemyMapWidth 4
#define enemyMapHeight 4
#define enemyMapBank 0

extern const unsigned char enemyMap[];

#endif

/* End of ENEMYMAP.H */
