/*

 ENEMYMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Projects\Gameboy\Kartamancer\raw graphics\enemyHorseTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 192
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define enemyMapWidth 4
#define enemyMapHeight 4
#define enemyMapBank 0

const unsigned char enemyMap[] =
{
  0xB0,0xB0,0xB0,0xBA,
  0xB1,0xB3,0xB9,0xBB,
  0xB4,0xB6,0xBC,0xBE,
  0xB5,0xB0,0xBD,0xBF
};

/* End of ENEMYMAP.C */
