/*

 ROOM2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 26
   Tile set      : C:\Projects\Gameboy\Kartomancer\raw graphics\forestTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room2Map_h_INCLUDE
#define __room2Map_h_INCLUDE

#define room2MapWidth 20
#define room2MapHeight 26
#define room2MapBank 0

extern const unsigned char room2Map[];

#endif

/* End of ROOM2MAP.H */
