/*

 TITLECARDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 7
   Tile set      : C:\Projects\Gameboy\Kartomancer\raw graphics\titlecardTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __titlecardMap_h_INCLUDE
#define __titlecardMap_h_INCLUDE

#define titlecardMapWidth 9
#define titlecardMapHeight 7
#define titlecardMapBank 0

extern const unsigned char titlecardMap[];

#endif

/* End of TITLECARDMAP.H */
