/*

 ENEMYNINJA2TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __enemyNinja2Tiles_h_INCLUDE
#define __enemyNinja2Tiles_h_INCLUDE

/* Bank of tiles. */
#define enemyNinja2TilesBank 0
/* Start of tile array. */
extern const unsigned char enemyNinja2Tiles[];

#endif

/* End of ENEMYNINJA2TILES.H */
