/*

 GLINTTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char glintTiles[] =
{
  0xC0,0x00,0xC0,0x00,0x60,0x00,0x60,0x00,
  0x30,0x00,0x30,0x00,0x18,0x00,0x18,0x00,
  0x18,0x00,0x18,0x00,0x0C,0x00,0x0C,0x00,
  0x06,0x00,0x06,0x00,0x03,0x00,0x03,0x00
};

/* End of GLINTTILES.C */
