/*

 HEALANIMTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 11

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __healAnimTiles_h_INCLUDE
#define __healAnimTiles_h_INCLUDE

/* Bank of tiles. */
#define healAnimTilesBank 0
/* Start of tile array. */
extern const unsigned char healAnimTiles[];

#endif

/* End of HEALANIMTILES.H */
