//AUTOGENERATED FILE FROM png2mtspr
#define player_TILE_H 8
#define player_WIDTH 16
#define player_HEIGHT 16
#define player_PIVOT_X 8
#define player_PIVOT_Y 8

extern const UINT8 player_data[432];
extern const metasprite_t* const player_metasprites[12];
